# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en la raíz del contenedor
WORKDIR /app

# Copia el archivo requirements.txt
COPY requirements.txt .

# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia todos los archivos locales del directorio src
COPY . .

# Copia el script de inicio
COPY run_container.sh /app/run_container.sh

# Dale permisos de ejecución al script
RUN chmod +x /app/run_container.sh

# Comando por defecto al iniciar el contenedor
CMD ["/app/run_container.sh"]
