# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo en la raíz del contenedor
WORKDIR /app

# Copia el archivo requirements.txt y instala las dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todos los archivos locales al contenedor (asegúrate de tener un .dockerignore adecuado)
COPY . .

# Define variables de entorno para las credenciales SFTP
ENV SFTP_USERNAME=${SFTP_USERNAME}
ENV SFTP_PASSWORD=${SFTP_PASSWORD}

# Define variables de entorno para las credenciales de AWS
# ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
# ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

# Comando por defecto al iniciar el contenedor
CMD ["python", "Codigo_ftp_Amazon.py"]
